node:
  name: Battle
  description: "The battle node"
  events:
    - play: "battlemusic.mid"
    - showgrid:
        todo: idk
    - loop:
        if: battleIsStillRaging
        then:
          - fallback:
            - foreach:  # std::for_each
                of: goodGuys
                  showmenu: 
                    name: "BattleMenu.yml"
                    pos: anchored
                    dims:
                      w: 50
                      h: 20
                    preconditions:
                      func: 
                        name: isAlive
                        args: this
                

