name: "node #2"
desc: "because i saID SO"
event: idk
edges:
  "The bedroom door to Michael's room":
    weight: 2
    endpointFilename: michaelnotbeinggay
    condition: imnotgay
  "Closet door":
    endpointFilename: michaelnotbeinggay
entities:
  michael: [1, 2]
  goomba:
    - [8, 9]
    - [6, 7]
    - [420, 69]
