node:
  name: Battle
  description: "The universal basic battle node"
  events:
    - fallback:
      - foreach:
          ofThe: goodGuys
          showMenu: 
            name: "BattleMenu.yml"
            pos:
              x: 20
              y: 10
            preconditions:
              bitIsSet:
                number: 5
                bitset: someBitSet
            

