node:
  name: Battle
  description: "The battle node"
  events:
    - fallback:
      - foreach:
          in: goodGuys
          showmenu: 
            name: "BattleMenu.yml"
            pos: anchored
            dims:
              w: 50
              h: 20
            preconditions:
              - bitIsSet:
                  name: someBitset
                  idx: 5
            

