menu:
  name: "Battle Menu"
  description: "Menu for each character to choose a battle action"
  items:
    - name: "Fight"
      showmenu: 
        fromfunc:
          name: getEnemies
          args: this
        onSelect:
          func:
            name: fight
            args: {src: this, dst: selection}
      relpos:
        x: 1
        y: 1
      dims:
        w: 20
        h: 7
    - name: "Magic"
      showmenu:
        fromfunc:
          name: getSpells
          args: this
        onSelect:
          showmenu:
            info: name
            from: enemies
      relpos:
        x: 1
        y: 1
      dims:
        w: 20
        h: 7
    - name: "Items"
      show: items
      relpos:
        x: 1
        y: 1
      dims:
        w: 20
        h: 7

      
