# custom, nested quirks
Trigger1:
  tree: test-tree
  priority: 5
  freq: 1000 # (ms) optional
  reps: 5# optional
Trigger2:
  tree: test-tree
  priority: 5
  freq: 1000 # (ms) optional
  reps: 5# optional

# Entity's entrypoint quirks
onStart:  # optional
  tree: tt2
  priority: 7
  freq: 1000 # (ms) optional
  reps: 5# optional
onInput:  # optional
  tree: onInput
  priority: 100
  freq: 1000 # (ms) optional
  reps: 5# optional
onTimer:  # optional
  tree: onInput
  priority: 100
  freq: 1000 # (ms) optional
  reps: 5# optional
onCollision: # optional
  tree: onInput
  priority: 100
  freq: 1000 # (ms) optional
  reps: 5# optional

